# fly.toml app configuration file for Fly.io
#
# Run 'fly launch' to create initial app
# Run 'fly deploy' to deploy

app = "optionbotpro"
primary_region = "iad"  # US East (Virginia) - closest to markets
kill_signal = "SIGTERM"
kill_timeout = 5

[build]
  [build.args]
    RUBY_VERSION = "3.2.0"

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

# Persistent volume for SQLite database
[mounts]
  source = "data"
  destination = "/data"

# Background worker process
[processes]
  web = "rails server -b 0.0.0.0 -p 3000"
  worker = "bundle exec sidekiq"

# Auto-scaling configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512