# Nixpacks configuration for Railway deployment
# This tells Railway how to build your Rails app without Docker

[phases.setup]
nixPkgs = ["ruby_3_2", "nodejs_20", "sqlite", "gcc"]
aptPkgs = ["libsqlite3-dev", "build-essential", "libssl-dev", "libreadline-dev", "zlib1g-dev"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "gem install bundler",
    "bundle config set --local deployment false",
    "bundle config set --local without 'development test'",
    "bundle install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "bundle exec rails assets:precompile",
    "bundle exec rails db:prepare"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"

[variables]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
BUNDLE_WITHOUT = "development:test"