# Railway configuration - simple buildpack deployment
[build]
builder = "HEROKU"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[environments.production]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
BUNDLE_WITHOUT = "development test"